export const passwords: Password[] = [
  {
    id: '1',
    name: 'Google',
    enter_value: 'victoraugusferreira@gmail.com',
    password_value: '123456',
    favorite: true,
    background: '#FFFFFF',
    icon: 'google',
    created_at: Date.now(),
    updated_at: Date.now(),
  },
  {
    id: '2',
    name: 'Facebook',
    enter_value: 'facebookvictor@gmail.com',
    password_value: '6548643516',
    favorite: true,
    background: '#FFFFFF',
    icon: 'facebook',
    created_at: Date.now(),
    updated_at: Date.now(),
  },
  {
    id: '3',
    name: 'Instagram',
    enter_value: 'instagramvictor@gmail.com',
    password_value: 'dwad754564',
    favorite: true,
    background: '#FFFFFF',
    icon: 'instagram',
    created_at: Date.now(),
    updated_at: Date.now(),
  },
];
