export let passwords: Password[] = [
  {
    id: '1',
    name: 'Google',
    enter_value: 'victoraugusferreira@gmail.com',
    password_value: '123456',
    favorite: true,
    background: '#FFFFFF',
    icon: 'google',
    categorie: 'Site',
    created_at: Date.now(),
    updated_at: Date.now(),
  },
  {
    id: '2',
    name: 'Facebook',
    enter_value: 'facebookvictor@gmail.com',
    password_value: '6548643516',
    favorite: false,
    background: '#FFFFFF',
    icon: 'facebook',
    categorie: 'Rede Social',
    created_at: Date.now(),
    updated_at: Date.now(),
  },
  {
    id: '3',
    name: 'Instagram',
    enter_value: 'instagramvictor@gmail.com',
    password_value: 'dwad754564',
    favorite: true,
    background: '#FFFFFF',
    icon: 'instagram',
    categorie: 'Rede Social',
    created_at: Date.now(),
    updated_at: Date.now(),
  },
  {
    id: '4',
    name: 'TikTok',
    enter_value: 'tiktok@gmail.com',
    password_value: 'dawdawd84',
    favorite: true,
    background: '#FFFFFF',
    icon: 'tiktok',
    categorie: 'Aplicativo',
    created_at: Date.now(),
    updated_at: Date.now(),
  },
  {
    id: '5',
    name: 'Nubank',
    enter_value: '3276497823/0001',
    password_value: '785481',
    favorite: false,
    background: '#FFFFFF',
    icon: 'nubank',
    categorie: 'Banco',
    created_at: Date.now(),
    updated_at: Date.now(),
  },
  {
    id: '6',
    name: 'Linkedin',
    enter_value: 'victorlinkedin@gmail.com',
    password_value: '4564',
    favorite: false,
    background: '#FFFFFF',
    icon: 'linkedin',
    categorie: 'Site',
    created_at: Date.now(),
    updated_at: Date.now(),
  },
];
